{
    "status": 1,
    "error": "",
    "data": {
        "aggregation": [
            {
                "key": "DJ",
                "count": 0
            },
            {
                "key": "现场",
                "count": 0
            },
            {
                "key": "广场舞",
                "count": 0
            },
            {
                "key": "伴奏",
                "count": 0
            },
            {
                "key": "铃声",
                "count": 0
            }
        ],
        "tab": "全部",
        "info": [
            {
                "pay_type_320": 0,
                "m4afilesize": 1252167,
                "price_sq": 0,
                "filesize": 4881344,
                "source": "",
                "bitrate": 128,
                "topic": "",
                "price": 0,
                "Accompany": 0,
                "fail_process_sq": 0,
                "singername": "放射空间",
                "pay_type": 0,
                "sourceid": 0,
                "topic_url": "",
                "fail_process_320": 0,
                "pkg_price": 0,
                "feetype": 0,
                "filename": "放射空间 - 终点‧起点",
                "price_320": 0,
                "extname": "mp3",
                "320hash": "02096e4a0f52c1be44d0cc7309c03b38",
                "mvhash": "",
                "privilege": 0,
                "group": [
                    {
                        "pay_type_320": 0,
                        "m4afilesize": 1252167,
                        "price_sq": 0,
                        "filesize": 4881344,
                        "source": "",
                        "bitrate": 128,
                        "topic": "",
                        "price": 0,
                        "Accompany": 0,
                        "fail_process_sq": 0,
                        "singername": "放射空间",
                        "pay_type": 0,
                        "sourceid": 0,
                        "topic_url": "",
                        "fail_process_320": 0,
                        "pkg_price": 0,
                        "feetype": 0,
                        "filename": "放射空间 - 终点‧起点",
                        "price_320": 0,
                        "extname": "mp3",
                        "320hash": "02096e4a0f52c1be44d0cc7309c03b38",
                        "mvhash": "",
                        "privilege": 0,
                        "album_id": "974774",
                        "ownercount": 3,
                        "rp_publish": 1,
                        "rp_type": "audio",
                        "audio_id": 981109,
                        "320filesize": 12203362,
                        "isnew": 0,
                        "duration": 305,
                        "pkg_price_sq": 0,
                        "pkg_price_320": 0,
                        "srctype": 1,
                        "songname": "终点‧起点",
                        "fail_process": 0,
                        "sqhash": "",
                        "album_name": "简单生活",
                        "hash": "0eb17f2473cf2aabe7c0b558641541c9",
                        "pay_type_sq": 0,
                        "320privilege": 0,
                        "sqprivilege": 0,
                        "sqfilesize": 0,
                        "othername": ""
                    }
                ],
                "album_id": "1220419",
                "ownercount": 3,
                "rp_publish": 1,
                "rp_type": "audio",
                "audio_id": 981109,
                "320filesize": 12203362,
                "isnew": 0,
                "duration": 305,
                "pkg_price_sq": 0,
                "pkg_price_320": 0,
                "srctype": 1,
                "songname": "终点‧起点",
                "fail_process": 0,
                "sqhash": "",
                "album_name": "起点.终点",
                "hash": "0eb17f2473cf2aabe7c0b558641541c9",
                "pay_type_sq": 0,
                "320privilege": 0,
                "sqprivilege": 0,
                "sqfilesize": 0,
                "othername": ""
            }
        ],
        "correctiontype": 0,
        "timestamp": 1496589682,
        "allowerr": 1,
        "total": 1,
        "istag": 0,
        "istagresult": 0,
        "forcecorrection": 0,
        "correctiontip": ""
    },
    "errcode": 0
}